################
# UseZED.cmake #
################

OPTION(WITH_ZED "Build with ZED device support?" OFF)

IF(WITH_ZED)
	FIND_PACKAGE(ZED 2 REQUIRED)
	FIND_PACKAGE(CUDA ${ZED_CUDA_VERSION} EXACT REQUIRED)
	
	INCLUDE_DIRECTORIES(${CUDA_INCLUDE_DIRS})
	INCLUDE_DIRECTORIES(${ZED_INCLUDE_DIRS})
  
	ADD_DEFINITIONS(-DCOMPILE_WITH_ZED)
ENDIF()
